#!/bin/bash

RESET='\033[0m'
RED='\033[01;31m'
YELLOW='\033[01;32m'

FORBIDDEN=('test.only' "console.log('### ")
FOUND=''

for file in `git diff --cached --name-only`
do
  for forbidden in "${FORBIDDEN[@]}"
  do

    # the trick is here...use `git show :file` to output what is staged
    if echo `git show :$file` | grep -q "$forbidden"; then
      FOUND+="${RED}$i contains ${RESET}\"$forbidden\"\n"
    fi
  done
done

# if FOUND is not empty, reject the commit

if [[ ! -z $FOUND ]]; then
  printf "${YELLOW}\nCOMMIT REJECTED \n"
  printf "$FOUND"
  exit 1
fi

# nothing found? let the commit happen
exit 0
